export USER_DOTFILES_PATH="XXX_USER_DOTFILES_PATH_XXX"
export DOTLYX_HOME_PATH="$USER_DOTFILES_PATH/modules/dotlyx"
export NIX_CONFIG_HOME="$USER_DOTFILES_PATH/modules/nix"
export ZIM_HOME="$USER_DOTFILES_PATH/modules/zim"
